version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.19.4"
replacements:
  group: "dev.tr7zw"
  name: "GraphUtil"
  id: "graphutil"
  version: "1.0.0"
  author: "tr7zw"
  dependencies: ""
  relocationpackage: "dev.tr7zw.graphutil"
  licensename: "LICENSE"
  curseforgeid: "681955"
  modrinthid: "cpBmCs66"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  GU-Fabric:
    template: "Fabric"
  GU-Forge:
    template: "Forge"