modLoader="javafml"
loaderVersion="[35,)"
license="tr7zw Protective License"
[[mods]]
modId="graphutil"
version="1.0.0"
displayName="GraphUtil"
authors="tr7zw"
description='''
Adds more settings to the F3 graphs.
'''
[[dependencies.graphutil]]
    modId="minecraft"
    mandatory=true
    versionRange="1.19.4"
    ordering="NONE"
    side="CLIENT"
